// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PS_Core","status":true,"description":"임의로 이벤트 처리를 잠시 기다리게 합니다","parameters":{}},
{"name":"PS_CustomWait","status":true,"description":"임의로 이벤트 처리를 잠시 기다리게 합니다","parameters":{}},
{"name":"PS_AdvancedTimer","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"PS_TextSound","status":true,"description":"","parameters":{}},
{"name":"PS_GoToArmy","status":true,"description":"","parameters":{}},
{"name":"PS_FreeMove","status":false,"description":"","parameters":{}},
{"name":"SAN_ResidualSprites","status":false,"description":"残像スプライツ 1.0.2\nキャラクターの残像スプライトを生成します。","parameters":{}}
];
